# Generated by Django 4.2.23 on 2025-06-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('plazaid', models.CharField(blank=True, db_column='PLAZAID', max_length=10, null=True)),
                ('plazaname', models.CharField(blank=True, db_column='PLAZANAME', max_length=100, null=True)),
                ('lane', models.CharField(blank=True, db_column='LANE', max_length=10, null=True)),
                ('sequence', models.CharField(db_column='SEQUENCE', max_length=20, primary_key=True, serialize=False)),
                ('collectorid', models.CharField(blank=True, db_column='COLLECTORID', max_length=20, null=True)),
                ('capturedate', models.DateTimeField(blank=True, db_column='CAPTUREDATE', null=True)),
                ('transtype', models.CharField(blank=True, db_column='TRANSTYPE', max_length=20, null=True)),
                ('vehicle_class', models.CharField(blank=True, db_column='CLASS', max_length=5, null=True)),
                ('regnumber', models.CharField(blank=True, db_column='REGNUMBER', max_length=20, null=True)),
                ('fare', models.DecimalField(blank=True, db_column='FARE', decimal_places=2, max_digits=10, null=True)),
                ('paytype', models.CharField(blank=True, db_column='PAYTYPE', max_length=10, null=True)),
                ('pic', models.BinaryField(blank=True, db_column='PIC', max_length='max', null=True)),
                ('shift', models.CharField(blank=True, db_column='SHIFT', max_length=10, null=True)),
            ],
            options={
                'db_table': '[TRANSACTION]',
                'ordering': ['-capturedate'],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
