# Generated by Django 4.2.23 on 2025-06-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'managed': False, 'ordering': ['-capturedate']},
        ),
    ]
