# Generated by Django 4.2.23 on 2025-06-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        ('transactions', '0003_make_transaction_readonly'),
    ]

    operations = [
    ]
