# Generated by Django 4.2.23 on 2025-06-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_merge_0002_initial_0003_make_transaction_readonly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': (), 'managed': True, 'ordering': ['-capturedate']},
        ),
    ]
